In [ ]:
import pandas as pd

import numpy as np

import matplotlib

import matplotlib.pyplot as plt
%matplotlib inline

import seaborn as sns

from collections import Counter

In [ ]:
pd.set_option('display.max_rows', 5000)
pd.set_option('display.max_columns', 5000)
pd.set_option('display.width', 5000)

In [ ]:
from sklearn import datasets

from sklearn.model_selection import train_test_split

from sklearn.metrics import confusion_matrix

from sklearn.metrics import classification_report

import sklearn.metrics as metrics

from sklearn.preprocessing import MinMaxScaler

from sklearn.preprocessing import StandardScaler

from sklearn import preprocessing

le = preprocessing.LabelEncoder()

from sklearn.metrics import precision_score

from sklearn.metrics import f1_score

from sklearn.metrics import recall_score

from sklearn.externals import joblib

from sklearn.tree import export_graphviz

/usr/local/lib/python3.7/dist-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
from sklearn.ensemble import RandomForestClassifier

from sklearn.datasets import make_classification

from sklearn.ensemble import BaggingClassifier

from sklearn.ensemble import AdaBoostClassifier

from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
# The dataset has been reduced and reshaped to the following dataset below for optimal machine learning model performances 

# Link to the original dataset - https://www.unb.ca/cic/datasets/ids-2017.html

In [ ]:
filepath0 = "/content/drive/MyDrive/Excel_file_created/main_88000.csv"

In [ ]:
data0 = pd.read_csv(filepath0)

In [ ]:
frame = data0

In [ ]:
X = frame.drop([" Label"],axis=1)
Y = frame[" Label"]

In [ ]:
counter = Counter(Y)

for a, b in counter.items():
  dist = b/len(Y) * 100
  # print (f"Label={a},\t\t\t\t n={b} ({dist}%)")
  print (f"n={b} ({dist:.3f}%), \t Label={a}")

n=30000 (34.091%), 	 Label=BENIGN
n=19500 (22.159%), 	 Label=DDoS/Dos
n=15000 (17.045%), 	 Label=PortScan
n=8000 (9.091%), 	 Label=Brute Force
n=4000 (4.545%), 	 Label=Bot
n=7500 (8.523%), 	 Label=Web Attacks
n=4000 (4.545%), 	 Label=Infiltration


In [ ]:
scaler = StandardScaler()

In [ ]:
columns = X.columns

In [ ]:
X_std = scaler.fit_transform(X)

In [ ]:
X_std = pd.DataFrame(X_std, columns = columns)

In [ ]:
# Splitting Data into training and testing dataset

X_train, X_test, y_train, y_test = train_test_split(X_std, Y, test_size=0.3, random_state=101)

In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((61600, 36), (26400, 36), (61600,), (26400,))

In [ ]:
rf = RandomForestClassifier(max_depth=5, random_state=0)
# 6 

In [ ]:
rf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=5, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [ ]:
rf_predictions = rf.predict(X_test)

In [ ]:
rf_predictions

array(['Brute Force', 'BENIGN', 'PortScan', ..., 'BENIGN', 'DDoS/Dos',
       'PortScan'], dtype=object)

In [ ]:
print(confusion_matrix(y_test, rf_predictions))

[[8994    0    0    0    0    0    0]
 [   0 1242    0    0    0    0    1]
 [   0    0 2406    0    0    0    0]
 [   1    1    0 5905    0    0    0]
 [   0    0    0    0 1167    0    0]
 [   0    0    0   17    0 4442    0]
 [   0    0    0    5    0    0 2219]]


In [ ]:
print(classification_report(y_test, rf_predictions))

              precision    recall  f1-score   support

      BENIGN       1.00      1.00      1.00      8994
         Bot       1.00      1.00      1.00      1243
 Brute Force       1.00      1.00      1.00      2406
    DDoS/Dos       1.00      1.00      1.00      5907
Infiltration       1.00      1.00      1.00      1167
    PortScan       1.00      1.00      1.00      4459
 Web Attacks       1.00      1.00      1.00      2224

    accuracy                           1.00     26400
   macro avg       1.00      1.00      1.00     26400
weighted avg       1.00      1.00      1.00     26400



In [ ]:
rf.score(X_test, y_test)

0.9990530303030303

In [ ]:
# Bagging

# bg = BaggingClassifier(RandomForestClassifier(), max_samples=0.5, max_features = 1.0, n_estimators=20)
# bg.fit(X_train, y_train)

In [ ]:
# bg.score(X_test, y_test)

In [ ]:
# bg_predictions = bg.predict(X_test)
# print(classification_report(y_test, bg_predictions))
# print(confusion_matrix(y_test, bg_predictions))

In [ ]:
# Boosting

boostin = AdaBoostClassifier(RandomForestClassifier(), n_estimators=5, learning_rate = 1)
# boostin = GradientBoostingClassifier(RandomForestClassifier(), n_estimators=5 )
boostin.fit(X_train, y_train)

AdaBoostClassifier(algorithm='SAMME.R',
                   base_estimator=RandomForestClassifier(bootstrap=True,
                                                         ccp_alpha=0.0,
                                                         class_weight=None,
                                                         criterion='gini',
                                                         max_depth=None,
                                                         max_features='auto',
                                                         max_leaf_nodes=None,
                                                         max_samples=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                       

In [ ]:
boostin.score(X_test, y_test)

In [ ]:
boostin_predictions = boostin.predict(X_test)
print(classification_report(y_test, rf_predictions))